# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &default
  s3_access_key_id: AKIAILFC4IUANKGNBDZA
  s3_secret_access_key: 1Lv7Exvx3P2dDOaXzbjn5pqlq3yvKU71L16sHWd7
  s3_region: ap-south-1

development:
  secret_key_base: a9babe1c7d8e7e320e4b46f3385f28455d36f2ab5553c82666493cd4a60819b216a78b30472a49cdcdb5d2d030379a8ceb8d99b4f8ecaf0e7f5892613d43ac19
  s3_bucket: turnstr2-development
  s3_host_name: s3.ap-south-1.amazonaws.com
  firebase_server_api_key: AAAA8RDsLvc:APA91bEaDPTpc5jNOEOQbz8jjPaBA2_sgzsXK-XzJbffSmayzutm49ztX2Sh70ndF1Q5TINT0Dcxo14jF4Rub32BqAC9aaKtte1UToeTHCDXlbCMUQ_vlIzCzo4MnXu8FFrUo8D_undf

test:
  secret_key_base: 3b048c05a8a696322b18adf60252819ca737ce5493aae1bb560f15ef9db5aa3ee36ff12222144941018625cff806d7924185d62eb209a2f8a979299eb4260f97

staging:
  <<: *default
  secret_key_base: 6bb1a2f50babb8def7d57ee596bf2336f7a708dad6978efe4608d9cb4d6036f45bde7be02c38092129d79ebb0892fffe07d6a020da6c93c2576ecc7f560ac102
  host: fathomless-retreat-45620.herokuapp.com
  mailgun_api_key:
  mailgun_domain: .mailgun.org

  s3_access_key_id: AKIAJKM6ZTKFJQYSWBLQ
  s3_secret_access_key: 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
  s3_region: us-west-2

  s3_bucket: turnstr2-staging
  s3_host_name: s3-us-west-2.amazonaws.com
  firebase_server_api_key: AAAA8RDsLvc:APA91bEaDPTpc5jNOEOQbz8jjPaBA2_sgzsXK-XzJbffSmayzutm49ztX2Sh70ndF1Q5TINT0Dcxo14jF4Rub32BqAC9aaKtte1UToeTHCDXlbCMUQ_vlIzCzo4MnXu8FFrUo8D_undf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 39d881d208c9f74cd5b568648a5242ae60e88336084405decc3762e084d63bd871db8d6551a0adefd39734a5a86a4f0060ad7d41c638aa71e99d51d6dd6335b0
  s3_access_key_id: AKIAJKM6ZTKFJQYSWBLQ
  s3_secret_access_key: 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
  s3_region: us-west-2

  s3_bucket: turnstr2-production
  s3_host_name: s3-us-west-2.amazonaws.com

  firebase_server_api_key: AAAA8RDsLvc:APA91bEaDPTpc5jNOEOQbz8jjPaBA2_sgzsXK-XzJbffSmayzutm49ztX2Sh70ndF1Q5TINT0Dcxo14jF4Rub32BqAC9aaKtte1UToeTHCDXlbCMUQ_vlIzCzo4MnXu8FFrUo8D_undf

